on:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup R dep
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::knitr
            any::rmarkdown
            any::readr
            any::DBI
            any::RSQLite
            any::dplyr
            any::dbplyr

      - name: Render home slides
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: index.qmd

      - name: Render home slides
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: select/index.qmd

      - name: Render filter slides
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: filter/index.qmd

      - name: Render aggregate slides
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: aggregate/index.qmd

      - name: Render aggregate slides
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: aggregate-2/index.qmd

      - name: Render join slides
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: join/index.qmd

      - name: Render tidyverse slides
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: tidyverse/index.qmd

      - name: Create CNAME to _slides folder
        run: echo 'sql.breant.art' > _slides/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _slides
